# Subpackage for slide generator modules
from .constants import get_reference_template
from .static_content import get_static_devotional_content
from .fallbacks import (
    get_fallback_morning_prayer,
    get_fallback_readings,
    get_fallback_data,
)
from .parsers import (
    extract_antiphon_and_psalm_info,
    extract_antiphon,
    extract_psalm_verses_from_html,
    extract_psalm_verses,
    get_fallback_verses,
    extract_canticle_verses,
    get_fallback_canticle_verses,
    extract_canticle_info,
    extract_short_reading,
    extract_responsory_from_html,
    extract_responsory,
    extract_gospel_antiphon,
    extract_benedictus_verses,
    extract_intercessions_text,
    extract_concluding_prayer,
    extract_first_reading_citation,
    extract_first_reading_verses,
    extract_psalm_citation,
    extract_psalm_response_verses,
    extract_gospel_acclamation,
    extract_gospel_citation,
    extract_gospel_verses,
    extract_intercessions_html,
)
from .slides import (
    create_initial_blank_slide,
    create_daily_morning_prayer_image_slide,
    create_heart_of_jesus_slide,
    create_heart_of_jesus_prayer_slides,
    create_oh_sacred_heart_slide,
    create_oh_sacred_heart_prayer_slides,
    create_novena_sacred_heart_slide,
    create_soul_of_christ_slides,
    create_prayer_of_thanksgiving_slides,
    create_novena_of_confidence_slides,
    create_novena_prayer_slides,
    create_salve_regina_slides,
    create_prayer_to_st_michael_slides,
    create_jubilee_prayer_slides,
    create_st_joseph_prayer_image_slide,
    create_st_joseph_prayer_text_slides,
    create_lords_prayer_slide,
)
from .generator import bbgrlslidegeneratorv1

__all__ = [
    "get_reference_template",
    "get_static_devotional_content",
    "get_fallback_morning_prayer",
    "get_fallback_readings",
    "get_fallback_data",
    # parsers
    "extract_antiphon_and_psalm_info",
    "extract_antiphon",
    "extract_psalm_verses_from_html",
    "extract_psalm_verses",
    "get_fallback_verses",
    "extract_canticle_verses",
    "get_fallback_canticle_verses",
    "extract_canticle_info",
    "extract_short_reading",
    "extract_responsory_from_html",
    "extract_responsory",
    "extract_gospel_antiphon",
    "extract_benedictus_verses",
    "extract_intercessions_text",
    "extract_concluding_prayer",
    "extract_first_reading_citation",
    "extract_first_reading_verses",
    "extract_psalm_citation",
    "extract_psalm_response_verses",
    "extract_gospel_acclamation",
    "extract_gospel_citation",
    "extract_gospel_verses",
    "extract_intercessions_html",
    # slides
    "create_initial_blank_slide",
    "create_daily_morning_prayer_image_slide",
    "create_heart_of_jesus_slide",
    "create_heart_of_jesus_prayer_slides",
    "create_oh_sacred_heart_slide",
    "create_oh_sacred_heart_prayer_slides",
    "create_novena_sacred_heart_slide",
    "create_soul_of_christ_slides",
    "create_prayer_of_thanksgiving_slides",
    "create_novena_of_confidence_slides",
    "create_novena_prayer_slides",
    "create_salve_regina_slides",
    "create_prayer_to_st_michael_slides",
    "create_jubilee_prayer_slides",
    "create_st_joseph_prayer_image_slide",
    "create_st_joseph_prayer_text_slides",
    "create_lords_prayer_slide",
    # orchestrator
    "bbgrlslidegeneratorv1",
]
